# Tyk developer pipeline -- perform validation and linting of API definitions and policies if needed for dev env APIs.
# This dev workflow will triggered if any PRs have been made specifically to the dev directory.
name: Tyk Development Workflow

# Execute workflow on dev pull requests
on:
    pull_request:
        paths:
            - 'dev/**'
    push:
        paths:
            - 'dev/**'

jobs:
    # Run linter and validation workflow
    tyk-lint:
        uses: ./.github/workflows/tyk-lint.yml
        with:
            environment: 'dev'
    
    # Set up staging APIs and Policies if the Dev assets pass the linter / validation
    tyk-set-up-staging:
        needs: tyk-lint
        uses: ./.github/workflows/tyk-staging.yml
        secrets: inherit
    
    # Set up prod APIs and Policies if the Dev assets pass the linter / validation
    tyk-set-up-prod:
        needs: tyk-set-up-staging
        uses: ./.github/workflows/tyk-production.yml
        secrets: inherit