name: Generate Production Tyk Assets

# Perform the env promotion only on push to main branch
on:
    push:
      branches: [ main ]

jobs:
    env-promotion:
        runs-on: ubuntu-latest
                
        steps:
        # Check out the current repo and fetch only the current commits (JTBD)
        - name: 'Checkout Repository'
          uses: actions/checkout@v4
          with:
            fetch-depth: 1
            